import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('aidd', {
  notify: (input: unknown) => ipcRenderer.invoke('app:notify', input),
  showItemInFolder: (filePath: string) => ipcRenderer.invoke('app:showItemInFolder', filePath),
  selectProjectFolder: () => ipcRenderer.invoke('project:selectFolder'),
  listProjects: () => ipcRenderer.invoke('project:list'),
  forgetProject: (projectId: string) => ipcRenderer.invoke('project:forget', projectId),
  readProjectStatus: (projectPath: string) => ipcRenderer.invoke('project:status', projectPath),
  readHomeWork: (projectPath: string) => ipcRenderer.invoke('project:homeWork', projectPath),
  validateProject: (projectPath: string) => ipcRenderer.invoke('project:validate', projectPath),
  repairProject: (projectPath: string) => ipcRenderer.invoke('project:repair', projectPath),
  readProjectSetup: (projectPath: string) => ipcRenderer.invoke('project:setup', projectPath),
  prepareFoundationReviewPackage: (projectPath: string) => ipcRenderer.invoke('project:prepareFoundationReviewPackage', projectPath),
  prepareFoundationDragFile: (input: unknown) => ipcRenderer.invoke('drag:prepareFoundationFile', input),
  prepareMarkdownDragFile: (input: unknown) => ipcRenderer.invoke('drag:prepareMarkdownFile', input),
  prepareNativeDragTestFile: () => ipcRenderer.invoke('drag:prepareNativeTestFile'),
  startNativeFileDrag: (filePath: string) => ipcRenderer.send('drag:startNativeFile', filePath),
  startFileDrag: (filePath: string) => ipcRenderer.send('drag:startNativeFile', filePath),
  readWorkflowDocuments: (projectPath: string) => ipcRenderer.invoke('project:workflowDocuments', projectPath),
  saveWorkflowDocument: (input: unknown) => ipcRenderer.invoke('project:saveWorkflowDocument', input),
  saveFoundationDocument: (input: unknown) => ipcRenderer.invoke('project:saveFoundationDocument', input),
  defineStandards: (input: unknown) => ipcRenderer.invoke('project:defineStandards', input),
  createComponent: (input: unknown) => ipcRenderer.invoke('project:createComponent', input),
  readComponent: (input: unknown) => ipcRenderer.invoke('project:readComponent', input),
  updateComponent: (input: unknown) => ipcRenderer.invoke('project:updateComponent', input),
  createCapability: (input: unknown) => ipcRenderer.invoke('project:createCapability', input),
  readCapability: (input: unknown) => ipcRenderer.invoke('project:readCapability', input),
  updateCapability: (input: unknown) => ipcRenderer.invoke('project:updateCapability', input),
  createDeliveryPackageFromCapability: (input: unknown) => ipcRenderer.invoke('project:createDeliveryPackageFromCapability', input),
  readDeliveryPackages: (projectPath: string) => ipcRenderer.invoke('project:readDeliveryPackages', projectPath),
  deleteDeliveryPackage: (input: unknown) => ipcRenderer.invoke('project:deleteDeliveryPackage', input),
  reorderDeliveryPackage: (input: unknown) => ipcRenderer.invoke('project:reorderDeliveryPackage', input),
  readDeliveryPackage: (input: unknown) => ipcRenderer.invoke('project:readDeliveryPackage', input),
  saveDeliveryPackage: (input: unknown) => ipcRenderer.invoke('project:saveDeliveryPackage', input),
  createDeliveryPackagePhase: (input: unknown) => ipcRenderer.invoke('project:createDeliveryPackagePhase', input),
  assembleDeliveryPackage: (input: unknown) => ipcRenderer.invoke('project:assembleDeliveryPackage', input),
  readDecisions: (projectPath: string) => ipcRenderer.invoke('project:readDecisions', projectPath),
  createDecision: (input: unknown) => ipcRenderer.invoke('project:createDecision', input),
  readSourceReference: (projectPath: string) => ipcRenderer.invoke('project:readSourceReference', projectPath),
  readSourceProjects: (projectPath: string) => ipcRenderer.invoke('project:readSourceProjects', projectPath),
  addSourceProject: (projectPath: string) => ipcRenderer.invoke('project:addSourceProject', projectPath),
  selectSourceDirectory: (projectPath: string) => ipcRenderer.invoke('project:selectSourceDirectory', projectPath),
  createProject: (input: unknown) => ipcRenderer.invoke('project:create', input),
  openExistingProject: () => ipcRenderer.invoke('project:openExisting'),
  gitIdentity: {
    read: () => ipcRenderer.invoke('gitIdentity:read'),
    save: (input: unknown) => ipcRenderer.invoke('gitIdentity:save', input)
  },
  gitSync: {
    readSettings: (projectPath: string) => ipcRenderer.invoke('gitSync:readSettings', projectPath),
    saveSettings: (input: unknown) => ipcRenderer.invoke('gitSync:saveSettings', input),
    testConnection: (input: unknown) => ipcRenderer.invoke('gitSync:testConnection', input),
    clearToken: (projectPath: string) => ipcRenderer.invoke('gitSync:clearToken', projectPath),
    getProjectConnectionStatus: (projectPath: string) => ipcRenderer.invoke('gitSync:getProjectConnectionStatus', projectPath),
    connectProject: (projectPath: string) => ipcRenderer.invoke('gitSync:connectProject', projectPath)
  },
  readText: (filePath: string) => ipcRenderer.invoke('fs:readText', filePath),
  writeText: (filePath: string, content: string) => ipcRenderer.invoke('fs:writeText', filePath, content)
});
