import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Plus, Puzzle, Save } from 'lucide-react';
import { AiddMarkdownEditor } from './editor/AiddMarkdownEditor';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Input } from './ui/input';
import { Select } from './ui/select';
import { Label } from './ui/label';
import { Alert, AlertDescription, AlertTitle } from './ui/alert';

const lifecycleOptions: AiddSetupStatus[] = ['not-started', 'draft', 'in-review', 'active', 'deprecated', 'complete', 'skipped'];
type ComponentView = 'list' | 'new' | 'edit';
function statusLabel(status?: string) { return (status ?? 'draft').replace(/-/g, ' '); }

export function Components({ activeProject }: { activeProject?: AiddTrackedProject | null }) {
  const [setup, setSetup] = useState<AiddProjectSetupState | null>(null);
  const [sourceProjects, setSourceProjects] = useState<AiddSourceCodeProject[]>([]);
  const [view, setView] = useState<ComponentView>('list');
  const [editingSlug, setEditingSlug] = useState<string | null>(null);
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [status, setStatus] = useState<AiddSetupStatus>('draft');
  const [selectedSourceProjects, setSelectedSourceProjects] = useState<string[]>([]);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const load = async () => { if (!activeProject?.path) return; const [nextSetup, nextSourceProjects] = await Promise.all([window.aidd.readProjectSetup(activeProject.path), window.aidd.readSourceProjects(activeProject.path)]); setSetup(nextSetup); setSourceProjects(nextSourceProjects); };
  useEffect(() => { load().catch((err) => setError(String(err))); }, [activeProject?.path]);
  const statusCounts = useMemo(() => { const counts = new Map<string, number>(); for (const component of setup?.components ?? []) counts.set(component.status ?? 'draft', (counts.get(component.status ?? 'draft') ?? 0) + 1); return counts; }, [setup?.components]);
  const resetForm = () => { setEditingSlug(null); setTitle(''); setDescription(''); setStatus('draft'); setSelectedSourceProjects([]); };
  const backToList = () => { resetForm(); setView('list'); };
  const openEdit = async (slug: string) => { if (!activeProject?.path) return; setError(null); try { const component = await window.aidd.readComponent({ projectPath: activeProject.path, slug }); setEditingSlug(component.slug); setTitle(component.title); setDescription(component.description || ''); setStatus((component.status as AiddSetupStatus) || 'draft'); setSelectedSourceProjects(component.sourceProjects || []); setView('edit'); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } };
  const createComponent = async () => { if (!activeProject?.path) return; setSaving(true); setError(null); try { const next = await window.aidd.createComponent({ projectPath: activeProject.path, title, description, status, sourceProjects: selectedSourceProjects }); setSetup(next); backToList(); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setSaving(false); } };
  const updateComponent = async () => { if (!activeProject?.path || !editingSlug) return; setSaving(true); setError(null); try { const next = await window.aidd.updateComponent({ projectPath: activeProject.path, slug: editingSlug, title, description, status, sourceProjects: selectedSourceProjects }); setSetup(next); backToList(); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setSaving(false); } };
  const toggleSourceProject = (projectId: string) => setSelectedSourceProjects((current) => current.includes(projectId) ? current.filter((item) => item !== projectId) : [...current, projectId]);
  if (!activeProject) return <div className="flex h-full items-center justify-center p-6"><Card><CardHeader><CardTitle>No project selected</CardTitle></CardHeader></Card></div>;

  if (view === 'list') return <div className="flex h-full flex-col overflow-hidden"><header className="flex h-16 shrink-0 items-center justify-between border-b px-6"><div><h1 className="text-xl font-semibold">Components</h1><p className="text-sm text-muted-foreground">Map apps, services, modules, libraries and workflows.</p></div><Button onClick={() => { resetForm(); setView('new'); }}><Plus className="h-4 w-4" /> New Component</Button></header><main className="min-h-0 flex-1 overflow-auto p-6">{error && <Alert variant="destructive" className="mb-4"><AlertTitle>Error</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}<div className="mb-6 grid gap-3 md:grid-cols-4"><Metric label="Total" value={setup?.components.length ?? 0} /><Metric label="Draft" value={statusCounts.get('draft') ?? 0} /><Metric label="Active" value={statusCounts.get('active') ?? 0} /><Metric label="Deprecated" value={statusCounts.get('deprecated') ?? 0} /></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{setup?.components.map((component) => { const linkedCapabilities = setup.capabilities.filter((capability) => capability.components?.includes(component.slug)); return <Card key={component.slug} className="cursor-pointer hover:bg-accent" onClick={() => openEdit(component.slug)}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-base">{component.title}</CardTitle><CardDescription>{linkedCapabilities.length ? `${linkedCapabilities.length} linked capability/capabilities` : 'No capabilities linked yet'}</CardDescription></div><Badge variant="outline">{statusLabel(component.status)}</Badge></div></CardHeader><CardContent className="space-y-2">{linkedCapabilities.map((capability) => <Badge key={capability.slug} variant="secondary">{capability.title}</Badge>)}{linkedCapabilities.length === 0 && <p className="text-sm text-muted-foreground">Open to map source projects and lifecycle.</p>}</CardContent></Card>; })}{setup && setup.components.length === 0 && <Card className="md:col-span-2 xl:col-span-3"><CardHeader><Puzzle className="h-6 w-6" /><CardTitle>No components yet</CardTitle><CardDescription>Create components to represent the parts that make capabilities possible.</CardDescription></CardHeader><CardContent><Button onClick={() => { resetForm(); setView('new'); }}>New Component</Button></CardContent></Card>}</div></main></div>;

  const editorAction = view === 'edit' ? updateComponent : createComponent;
  return <div className="flex h-full flex-col overflow-hidden"><header className="flex h-16 shrink-0 items-center justify-between gap-3 border-b px-6"><div className="flex min-w-0 flex-1 items-center gap-2"><Button variant="ghost" size="icon" onClick={backToList}><ArrowLeft className="h-4 w-4" /></Button><Input className="max-w-lg text-base font-semibold" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Component name" /></div><Button onClick={editorAction} disabled={saving || !title.trim()}>{view === 'edit' ? <Save className="h-4 w-4" /> : <Plus className="h-4 w-4" />}{saving ? 'Saving...' : view === 'edit' ? 'Save' : 'Create'}</Button></header>{error && <div className="shrink-0 px-6 pt-4"><Alert variant="destructive"><AlertTitle>Error</AlertTitle><AlertDescription>{error}</AlertDescription></Alert></div>}<main className="grid min-h-0 flex-1 gap-4 overflow-hidden p-6 xl:grid-cols-[1fr_320px]"><Card className="flex min-h-0 flex-col"><CardHeader><CardTitle>Component description</CardTitle><CardDescription>Describe what this component is responsible for. The body is saved exactly as edited.</CardDescription></CardHeader><CardContent className="min-h-0 flex-1"><AiddMarkdownEditor value={description} onChange={setDescription} minHeight={520} /></CardContent></Card><aside className="space-y-4 overflow-auto"><Card><CardHeader><CardTitle>Lifecycle</CardTitle></CardHeader><CardContent className="space-y-3"><Label>Status</Label><Select value={status} onChange={(event) => setStatus(event.target.value as AiddSetupStatus)}>{lifecycleOptions.map((item) => <option key={item} value={item}>{statusLabel(item)}</option>)}</Select>{status === 'deprecated' && <Alert><AlertTitle>Deprecated</AlertTitle><AlertDescription>Avoid linking this component to new work unless migration/removal is intentional.</AlertDescription></Alert>}</CardContent></Card><Card><CardHeader><CardTitle>Source projects</CardTitle><CardDescription>Map this component to implementation directories.</CardDescription></CardHeader><CardContent className="space-y-2">{sourceProjects.length ? sourceProjects.map((project) => <label key={project.id} className="flex cursor-pointer items-start gap-3 rounded-lg border p-3 text-sm hover:bg-accent"><input className="mt-1" type="checkbox" checked={selectedSourceProjects.includes(project.id)} onChange={() => toggleSourceProject(project.id)} /><span><strong>{project.name}</strong><span className="block text-muted-foreground">{project.detectedType} · {project.path}</span></span></label>) : <p className="text-sm text-muted-foreground">No source projects yet. Add them from Source Code.</p>}</CardContent></Card></aside></main></div>;
}
function Metric({ label, value }: { label: string; value: number }) { return <Card><CardContent className="p-4"><div className="text-2xl font-semibold">{value}</div><div className="text-sm text-muted-foreground">{label}</div></CardContent></Card>; }
