import type { DeliveryBundle } from '../domain/types';
import { checkReadiness } from '../domain/readiness';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';

interface DeliveryPackagesProps { packages: DeliveryBundle[]; selectedId: string; onSelectPackage: (id: string) => void; onCreatePackage: () => void; }
const statusCopy: Record<string, string> = { draft: 'Draft', 'needs-review': 'Needs review', 'changes-requested': 'Changes requested', 'approved-for-ai': 'Approved', 'in-ai-execution': 'In execution', 'needs-verification': 'Needs verification', accepted: 'Accepted', superseded: 'Superseded' };
export function DeliveryPackages({ packages, selectedId, onSelectPackage, onCreatePackage }: DeliveryPackagesProps) {
  return <div className="flex h-full flex-col overflow-hidden"><header className="flex h-16 shrink-0 items-center justify-between border-b px-6"><div><h1 className="text-xl font-semibold">Delivery</h1><p className="text-sm text-muted-foreground">Prioritise and prepare delivery packages.</p></div><Button onClick={onCreatePackage}>New Delivery Package</Button></header><main className="min-h-0 flex-1 overflow-auto p-6"><div className="grid gap-4 xl:grid-cols-4">{Object.entries(statusCopy).map(([status, label]) => { const items = packages.filter((item) => item.status === status); return <Card key={status}><CardHeader className="pb-3"><div className="flex items-center justify-between"><CardTitle className="text-base">{label}</CardTitle><Badge variant="outline">{items.length}</Badge></div></CardHeader><CardContent className="space-y-3">{items.map((item) => { const readiness = checkReadiness(item); return <button key={item.id} className={`w-full rounded-lg border p-3 text-left hover:bg-accent ${item.id === selectedId ? 'ring-2 ring-ring' : ''}`} onClick={() => onSelectPackage(item.id)}><div className="font-medium">{item.id} · {item.title}</div><div className="text-sm text-muted-foreground">{item.capability}</div><Badge variant="secondary" className="mt-2">{readiness.score}% ready</Badge></button>; })}{items.length === 0 && <p className="text-sm text-muted-foreground">No packages.</p>}</CardContent></Card>; })}</div></main></div>;
}
