import { useEffect, useState } from 'react';
import { CheckCircle2, CircleAlert, RefreshCw, Wrench } from 'lucide-react';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Alert, AlertDescription, AlertTitle } from './ui/alert';

function severityVariant(severity: string): 'default' | 'secondary' | 'destructive' | 'outline' { if (severity === 'error') return 'destructive'; if (severity === 'success') return 'secondary'; if (severity === 'warning') return 'outline'; return 'outline'; }

export function ProjectValidation({ activeProject }: { activeProject?: AiddTrackedProject | null }) {
  const [report, setReport] = useState<AiddProjectValidationReport | null>(null);
  const [repair, setRepair] = useState<AiddProjectRepairReport | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const run = async () => { if (!activeProject?.path) return; setBusy(true); setError(null); try { setReport(await window.aidd.validateProject(activeProject.path)); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setBusy(false); } };
  const fix = async () => { if (!activeProject?.path) return; setBusy(true); setError(null); try { const result = await window.aidd.repairProject(activeProject.path); setRepair(result); setReport(result.validation); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setBusy(false); } };
  useEffect(() => { run(); }, [activeProject?.path]);
  if (!activeProject) return <div className="flex h-full items-center justify-center p-6"><Card><CardHeader><CardTitle>No project selected</CardTitle></CardHeader></Card></div>;
  return <div className="flex h-full flex-col overflow-hidden"><header className="flex h-16 shrink-0 items-center justify-between border-b px-6"><div><h1 className="text-xl font-semibold">Validation</h1><p className="text-sm text-muted-foreground">Check project structure, readiness and safe repair actions.</p></div><div className="flex gap-2"><Button variant="outline" onClick={run} disabled={busy}><RefreshCw className="h-4 w-4" /> Run validation</Button><Button onClick={fix} disabled={busy}><Wrench className="h-4 w-4" /> Fix safe issues</Button></div></header><main className="min-h-0 flex-1 overflow-auto p-6">{error && <Alert variant="destructive" className="mb-4"><AlertTitle>Validation error</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}{repair && <Alert className="mb-4"><AlertTitle>{repair.changed ? 'Repair applied' : 'No repair needed'}</AlertTitle><AlertDescription>{repair.changes.length ? repair.changes.join(', ') : 'Project already matched safe repair expectations.'}</AlertDescription></Alert>}{report && <div className="space-y-6"><div className="grid gap-4 md:grid-cols-4"><Metric label="Score" value={`${report.score}%`} /><Metric label="Errors" value={report.summary.errors} /><Metric label="Warnings" value={report.summary.warnings} /><Metric label="Status" value={report.status} /></div>{report.nextActions.length > 0 && <Card><CardHeader><CardTitle>Next actions</CardTitle></CardHeader><CardContent className="space-y-2">{report.nextActions.map((action) => <div key={action} className="flex items-center gap-2 text-sm"><CircleAlert className="h-4 w-4" />{action}</div>)}</CardContent></Card>}{report.sections.map((section) => <Card key={section.id}><CardHeader><CardTitle>{section.title}</CardTitle></CardHeader><CardContent className="space-y-2">{section.items.map((item) => <div key={item.id} className="flex items-start justify-between gap-3 rounded-lg border p-3"><div className="flex items-start gap-3">{item.severity === 'success' ? <CheckCircle2 className="mt-0.5 h-4 w-4" /> : <CircleAlert className="mt-0.5 h-4 w-4" />}<div><div className="text-sm font-medium">{item.title}</div><div className="text-sm text-muted-foreground">{item.message}</div>{item.path && <code className="mt-1 block text-xs text-muted-foreground">{item.path}</code>}</div></div><Badge variant={severityVariant(item.severity)}>{item.severity}</Badge></div>)}</CardContent></Card>)}</div>}</main></div>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <Card><CardContent className="p-4"><div className="text-2xl font-semibold capitalize">{value}</div><div className="text-sm text-muted-foreground">{label}</div></CardContent></Card>; }
