import { useEffect, useState } from 'react';
import { Code2, FolderPlus } from 'lucide-react';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Alert, AlertDescription, AlertTitle } from './ui/alert';

export function SourceCode({ activeProject }: { activeProject?: AiddTrackedProject | null }) {
  const [projects, setProjects] = useState<AiddSourceCodeProject[]>([]);
  const [setup, setSetup] = useState<AiddProjectSetupState | null>(null);
  const [error, setError] = useState<string | null>(null);
  const load = async () => { if (!activeProject?.path) return; const [sourceProjects, projectSetup] = await Promise.all([window.aidd.readSourceProjects(activeProject.path), window.aidd.readProjectSetup(activeProject.path)]); setProjects(sourceProjects); setSetup(projectSetup); };
  useEffect(() => { load().catch((err) => setError(String(err))); }, [activeProject?.path]);
  const addProject = async () => { if (!activeProject?.path) return; const project = await window.aidd.addSourceProject(activeProject.path); if (project) await load(); };
  if (!activeProject) return <div className="flex h-full items-center justify-center p-6"><Card><CardHeader><CardTitle>No project selected</CardTitle></CardHeader></Card></div>;
  return <div className="flex h-full flex-col overflow-hidden"><header className="flex h-16 shrink-0 items-center justify-between border-b px-6"><div><h1 className="text-xl font-semibold">Source Code</h1><p className="text-sm text-muted-foreground">Register implementation directories and map them to components.</p></div><Button onClick={addProject}><FolderPlus className="h-4 w-4" /> Add source project</Button></header><main className="min-h-0 flex-1 overflow-auto p-6">{error && <Alert variant="destructive" className="mb-4"><AlertTitle>Error</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.map((project) => { const mappedComponents = setup?.components.filter((component) => component.sourceProjects?.includes(project.id)) ?? []; return <Card key={project.id}><CardHeader><div className="flex items-start gap-3"><Code2 className="mt-1 h-5 w-5" /><div className="min-w-0"><CardTitle className="truncate text-base">{project.name}</CardTitle><CardDescription className="truncate">{project.path}</CardDescription></div></div></CardHeader><CardContent className="space-y-3"><Badge variant="outline">{project.detectedType}</Badge><div className="flex flex-wrap gap-2">{project.indicators.map((indicator) => <Badge key={indicator} variant="secondary">{indicator}</Badge>)}</div><div><div className="mb-1 text-sm font-medium">Mapped components</div>{mappedComponents.length ? <div className="flex flex-wrap gap-2">{mappedComponents.map((component) => <Badge key={component.slug}>{component.title}</Badge>)}</div> : <p className="text-sm text-muted-foreground">No components mapped yet.</p>}</div></CardContent></Card>; })}{projects.length === 0 && <Card className="md:col-span-2 xl:col-span-3"><CardHeader><CardTitle>No source projects</CardTitle><CardDescription>Add implementation directories so components can reference code.</CardDescription></CardHeader><CardContent><Button onClick={addProject}>Add source project</Button></CardContent></Card>}</div></main></div>;
}
