#!/usr/bin/env node
import { promises as fs } from 'node:fs';
import path from 'node:path';
const ROOT=process.cwd();
const CONFIG=JSON.parse(await fs.readFile(path.join(ROOT,'aidd.config.json'),'utf8'));
const cmd=process.argv[2]; const args=process.argv.slice(3);
try{
 if(cmd==='check') await check(); else if(cmd==='list') await listAll(); else if(cmd==='component:create') await createComponent(args); else if(cmd==='component:list') await listComponents(); else if(cmd==='capability:create') await createCapability(args); else if(cmd==='capability:list') await listCapabilities(); else if(cmd==='bundle:create') await createBundle(args); else if(cmd==='bundle:ready') await readyBundle(args); else if(cmd==='bundle:export') await exportBundle(args); else if(cmd==='bundle:list') await listDelivery Packages(); else if(cmd==='delivery:roadmap') await roadmap(); else if(cmd==='standards:list') await standardsList(); else if(cmd==='standards:apply') await standardsApply(args); else if(cmd==='standards:show') await standardsShow(); else if(cmd==='standards:remove') await standardsRemove(args); else if(cmd==='capability') await capabilityPack(args); else if(cmd==='clean') await clean(); else help();
}catch(e){console.error(e.message);process.exit(1)}
function help(){console.log('AIDD commands: check, list, standards:list, standards:apply, component:create, capability:create, bundle:create, bundle:ready, bundle:export, delivery:roadmap')}
async function check(){for(const f of ['foundation/index.md','components/index.md','capabilities/index.md','delivery/index.md','delivery/packages/index.md','.aidd/scripts/aidd.mjs','.aidd/templates/component/index.md','.aidd/templates/capability/index.md','.aidd/templates/delivery-bundle/index.md']) await assert(f); const bad=[]; for(const f of ['scripts','templates','_template','components/_template','capabilities/_template','delivery/_template','delivery/packages/_template']) if(await exists(p(f))) bad.push(f); if(bad.length) throw new Error('Template/tooling clutter found:\n'+bad.map(x=>'- '+x).join('\n')); console.log('AIDD check passed.')}
async function assert(f){if(!(await exists(p(f)))) throw new Error('Missing required file: '+f)}
async function createComponent(a){const slug=pos(a)[0]; if(!slug) throw new Error('Component slug is required.'); const title=flag(a,'title')||titleFromSlug(slug); const dir=p(CONFIG.componentsDir,slug); if(await exists(dir)) throw new Error('Component already exists: '+slug); await copyDir(p('.aidd/templates/component'),dir); await repl(dir,{'__COMPONENT_SLUG__':slug,'__COMPONENT_TITLE__':title}); await writeJson(path.join(dir,'component.json'),{slug,title,status:'active',createdAt:new Date().toISOString(),owns:[],dependsOn:[],exposes:[]}); await refreshComponentsIndex(); console.log('Created component: '+slug)}
async function createCapability(a){const slug=pos(a)[0]; if(!slug) throw new Error('Capability slug is required.'); const title=flag(a,'title')||titleFromSlug(slug); const components=csv(flag(a,'components')); for(const m of components) if(!(await exists(p(CONFIG.componentsDir,m)))) throw new Error('Referenced component does not exist: '+m); const dir=p(CONFIG.capabilitiesDir,slug); if(await exists(dir)) throw new Error('Capability already exists: '+slug); await copyDir(p('.aidd/templates/capability'),dir); await repl(dir,{'__CAPABILITY_SLUG__':slug,'__CAPABILITY_TITLE__':title}); await writeJson(path.join(dir,'capability.json'),{slug,title,status:'active',components,createdAt:new Date().toISOString()}); await refreshCapabilitiesIndex(); await refreshComponentsIndex(); console.log('Created capability: '+slug)}
async function createBundle(a){const id=pos(a)[0]; if(!id) throw new Error('Bundle ID is required.'); const title=flag(a,'title')||titleFromSlug(id); const cap=flag(a,'capability'); if(!cap) throw new Error('--capability is required.'); const capMan=await readJson(p(CONFIG.capabilitiesDir,cap,'capability.json')); const dir=p(CONFIG.deliveryDelivery PackagesDir,id); if(await exists(dir)) throw new Error('Bundle already exists: '+id); await copyDir(p('.aidd/templates/delivery-bundle'),dir); await repl(dir,{'__BUNDLE_ID__':id,'__BUNDLE_TITLE__':title,'__CAPABILITY_SLUG__':cap,'__CAPABILITY_TITLE__':capMan.title}); await writeJson(path.join(dir,'bundle.json'),{id,title,status:'draft',capability:cap,components:capMan.components||[],sourceRoots:CONFIG.sourceRoots||[],priority:Number(flag(a,'priority')||100),createdAt:new Date().toISOString(),readyAt:null}); await fs.mkdir(path.join(dir,'exports'),{recursive:true}); await refreshDelivery PackagesIndex(); await roadmap(); console.log('Created delivery package: '+id)}
async function readyBundle(a){const id=pos(a)[0]; const dir=p(CONFIG.deliveryDelivery PackagesDir,id); if(!(await exists(dir))) throw new Error('Bundle not found: '+id); const files=['01-context.md','02-scope.md','03-design.md','04-implementation-plan.md','05-tasks.md','06-acceptance.md','07-review.md','08-validation.md','09-handoff.md']; const todos=[]; for(const f of files){const c=await fs.readFile(path.join(dir,f),'utf8'); if(c.includes('TODO')) todos.push(f)} if(todos.length) throw new Error('Bundle cannot be marked ready while TODO markers remain:\n'+todos.map(x=>'- '+x).join('\n')); const man=await readJson(path.join(dir,'bundle.json')); man.status='ready'; man.readyAt=new Date().toISOString(); await writeJson(path.join(dir,'bundle.json'),man); await refreshDelivery PackagesIndex(); await roadmap(); console.log('Marked bundle ready: '+id)}
async function exportBundle(a){const id=pos(a)[0]; const dir=p(CONFIG.deliveryDelivery PackagesDir,id); const man=await readJson(path.join(dir,'bundle.json')); if(man.status!=='ready') throw new Error(`Cannot export ${id}. Current status is ${man.status}. Run bundle:ready first.`); const cap=await readJson(p(CONFIG.capabilitiesDir,man.capability,'capability.json')); const exp=path.join(dir,'exports'); await fs.mkdir(exp,{recursive:true}); const standards=await readAppliedStandards(); const stds=standards.profiles.length?standards.profiles.map(s=>`- foundation/standards/${s.path}`).join('\n'):'- No standards profiles applied.'; const roots=(CONFIG.sourceRoots||[]).map(r=>`| ${r.id} | ${r.label||r.id} | ${r.path} | ${r.type||'generic'} |`).join('\n')||'| none | none | none | none |'; const mods=(man.components||[]).map(m=>`- components/${m}/02-boundaries.md`).join('\n')||'- No component boundaries referenced.'; let out=`# ${id} Agent Export\n\n## Source of Truth\n\nThis file is the implementation source of truth for this delivery package.\n\n## Bundle Metadata\n\n- Bundle ID: ${id}\n- Title: ${man.title}\n- Capability: ${cap.title}\n- Status at export: ${man.status}\n\n## Source Map\n\n| ID | Label | Path | Type |\n|---|---|---|---|\n${roots}\n\n## Applicable Standards\n\n${stds}\n\n## Component Boundary Rules\n\n${mods}\n`; for(const f of ['01-context.md','02-scope.md','03-design.md','04-implementation-plan.md','05-tasks.md','06-acceptance.md','07-review.md','08-validation.md','09-handoff.md']) out+='\n---\n\n'+await fs.readFile(path.join(dir,f),'utf8')+'\n'; await fs.writeFile(path.join(exp,`${id}.agent.md`),out); console.log('Generated agent export: '+path.relative(ROOT,path.join(exp,`${id}.agent.md`)))}
async function standardsList(){const profiles=await availableStandards(); console.log('Available standards profiles:'); for(const x of profiles) console.log(`  ${x.name} (${x.category})`); const presets=await readDirs(p('.aidd/templates/standards/presets')); console.log('\nAvailable presets:'); for(const x of presets) console.log('  '+x.replace(/\.json$/,''))}
async function standardsApply(a){let names=pos(a); const preset=flag(a,'preset'); if(preset){const pth=p('.aidd/templates/standards/presets',preset+'.json'); const pset=await readJson(pth); names=[...names,...(pset.profiles||[])]} if(!names.length) throw new Error('No standards profiles provided.'); const profiles=await availableStandards(); const map=new Map(profiles.map(x=>[x.name,x])); const st=await readAppliedStandards(); for(const n of names){const prof=map.get(n); if(!prof) throw new Error('Unknown standards profile: '+n); const out=p('foundation/standards',prof.category,prof.name+'.md'); await fs.mkdir(path.dirname(out),{recursive:true}); await fs.copyFile(prof.filePath,out); const rel=path.relative(p('foundation/standards'),out).replaceAll('\\','/'); if(!st.profiles.some(x=>x.name===prof.name)) st.profiles.push({name:prof.name,category:prof.category,path:rel});} st.updatedAt=new Date().toISOString(); await writeJson(p('foundation/standards/standards.json'),st); await refreshStandardsIndex(st); console.log('Applied standards: '+names.join(', '))}
async function standardsShow(){const st=await readAppliedStandards(); console.log('Applied standards:'); if(!st.profiles.length) console.log('  none'); for(const x of st.profiles) console.log(`  ${x.name} (${x.category})`)}
async function standardsRemove(a){const names=pos(a); const st=await readAppliedStandards(); st.profiles=st.profiles.filter(x=>!names.includes(x.name)); st.updatedAt=new Date().toISOString(); await writeJson(p('foundation/standards/standards.json'),st); await refreshStandardsIndex(st); console.log('Removed standards: '+names.join(', '))}
async function capabilityPack(a){const slug=pos(a)[0]; const dir=p(CONFIG.capabilitiesDir,slug); const man=await readJson(path.join(dir,'capability.json')); const outDir=p(CONFIG.deliveryDelivery PackagesDir,'_capability-packs'); await fs.mkdir(outDir,{recursive:true}); let out=`# ${man.title} Capability Pack\n\n`; for(const f of await fs.readdir(dir)){ if(f.endsWith('.md')) out+='\n---\n\n'+await fs.readFile(path.join(dir,f),'utf8')+'\n'} await fs.writeFile(path.join(outDir,`${slug}.capability.md`),out); console.log('Generated capability pack.')}
async function listAll(){await listComponents(); await listCapabilities(); await listDelivery Packages()}
async function listComponents(){const xs=await entities(CONFIG.componentsDir,'component.json'); console.log('Components:'); if(!xs.length) console.log('  none'); for(const x of xs) console.log(`  ${x.slug} — ${x.title} (${x.status})`)}
async function listCapabilities(){const xs=await entities(CONFIG.capabilitiesDir,'capability.json'); console.log('Capabilities:'); if(!xs.length) console.log('  none'); for(const x of xs) console.log(`  ${x.slug} — ${x.title} (${x.status}; components: ${(x.components||[]).join(', ')||'none'})`)}
async function listDelivery Packages(){const xs=await entities(CONFIG.deliveryDelivery PackagesDir,'bundle.json'); console.log('Delivery packages:'); if(!xs.length) console.log('  none'); for(const x of xs) console.log(`  ${x.id} — ${x.title} (${x.status}; capability: ${x.capability})`)}
async function clean(){for(const d of await readDirs(p(CONFIG.deliveryDelivery PackagesDir))){if(d.startsWith('_')) continue; await fs.rm(p(CONFIG.deliveryDelivery PackagesDir,d,'exports'),{recursive:true,force:true}); await fs.mkdir(p(CONFIG.deliveryDelivery PackagesDir,d,'exports'),{recursive:true})} console.log('Cleaned generated bundle exports.')}
async function refreshComponentsIndex(){const ms=await entities(CONFIG.componentsDir,'component.json'), cs=await entities(CONFIG.capabilitiesDir,'capability.json'); const active=ms.filter(x=>status(x)==='active'); const sec=['## Active components','',active.length?active.map(m=>`- [${m.title}](./${m.slug}/index.md)${cs.filter(c=>(c.components||[]).includes(m.slug)).length?' — capabilities: '+cs.filter(c=>(c.components||[]).includes(m.slug)).map(c=>`[${c.title}](../capabilities/${c.slug}/index.md)`).join(', '):''}`).join('\n'):'No active components yet.','','## Deprecated components','','No deprecated components.','','## Archived components','','No archived components.',''].join('\n'); await managed(p(CONFIG.componentsDir,'index.md'),'## Active components',sec)}
async function refreshCapabilitiesIndex(){const cs=await entities(CONFIG.capabilitiesDir,'capability.json'); const active=cs.filter(x=>status(x)==='active'); const sec=['## Active capabilities','',active.length?active.map(c=>`- [${c.title}](./${c.slug}/index.md)${(c.components||[]).length?' — components: '+c.components.join(', '):''}`).join('\n'):'No active capabilities yet.','','## Deprecated capabilities','','No deprecated capabilities.','','## Archived capabilities','','No archived capabilities.',''].join('\n'); await managed(p(CONFIG.capabilitiesDir,'index.md'),'## Active capabilities',sec)}
async function refreshDelivery PackagesIndex(){const bs=await entities(CONFIG.deliveryDelivery PackagesDir,'bundle.json'); const sec=['## Delivery Packages','',bs.length?bs.map(b=>`- [${b.title}](./${b.id}/index.md) — ${b.status}`).join('\n'):'No delivery packages yet.',''].join('\n'); await managed(p(CONFIG.deliveryDelivery PackagesDir,'index.md'),'## Delivery Packages',sec)}
async function roadmap(){const bs=await entities(CONFIG.deliveryDelivery PackagesDir,'bundle.json'); const statuses=['draft','planned','ready','in-progress','completed','archived']; const lines=['# Delivery Roadmap','','Generated from delivery package metadata.','']; for(const s of statuses){lines.push(`## ${titleFromSlug(s)}`,''); const group=bs.filter(b=>(b.status||'draft')===s); lines.push(group.length?group.map(b=>`- [${b.title}](./packages/${b.id}/index.md) — ${b.id}`).join('\n'):`No ${s} packages.`,'')} await fs.writeFile(p(CONFIG.deliveryDir,'roadmap.md'),lines.join('\n').trimEnd()+'\n'); await writeJson(p(CONFIG.deliveryDir,'roadmap.json'),{packages:bs.map(b=>({id:b.id,title:b.title,status:b.status,capability:b.capability,components:b.components||[],priority:b.priority||100}))}); console.log('Updated delivery roadmap.')}
async function availableStandards(){const root=p('.aidd/templates/standards/profiles'); const cats=await readDirs(root); const out=[]; for(const cat of cats){for(const f of await fs.readdir(path.join(root,cat),{withFileTypes:true})){if(f.isFile()&&f.name.endsWith('.md')) out.push({name:f.name.replace(/\.md$/,''),category:cat,filePath:path.join(root,cat,f.name)})}} return out.sort((a,b)=>a.name.localeCompare(b.name))}
async function readAppliedStandards(){const f=p('foundation/standards/standards.json'); if(!(await exists(f))) return {profiles:[],updatedAt:null}; const x=await readJson(f); x.profiles??=[]; return x}
async function refreshStandardsIndex(st){const lines=['# Standards','','Project-owned standards applied from AIDD profiles.','','## Applied Standards','']; lines.push(st.profiles.length?st.profiles.map(x=>`- [${titleFromSlug(x.name)}](./${x.path}) — ${x.category}`).join('\n'):'No standards profiles have been applied yet.'); await fs.writeFile(p('foundation/standards/index.md'),lines.join('\n')+'\n')}
async function entities(dirName,manifest){const dir=p(dirName); if(!(await exists(dir))) return []; const out=[]; for(const e of await fs.readdir(dir,{withFileTypes:true})){if(!e.isDirectory()||e.name.startsWith('_')) continue; const mf=path.join(dir,e.name,manifest); if(await exists(mf)) out.push(await readJson(mf))} return out.sort((a,b)=>(a.title||a.id).localeCompare(b.title||b.id))}
async function readDirs(dir){if(!(await exists(dir))) return []; const es=await fs.readdir(dir,{withFileTypes:true}); return es.filter(e=>e.isDirectory()||e.isFile()).map(e=>e.name)}
async function copyDir(from,to){await fs.mkdir(to,{recursive:true}); for(const e of await fs.readdir(from,{withFileTypes:true})){const s=path.join(from,e.name),t=path.join(to,e.name); if(e.isDirectory()) await copyDir(s,t); else await fs.copyFile(s,t)}}
async function repl(root,replacements){for(const e of await fs.readdir(root,{withFileTypes:true})){const full=path.join(root,e.name); if(e.isDirectory()){await repl(full,replacements);continue} if(!/\.(md|json)$/i.test(e.name)) continue; let c=await fs.readFile(full,'utf8'); for(const [a,b] of Object.entries(replacements)) c=c.split(a).join(b); await fs.writeFile(full,c)}}
async function exists(f){try{await fs.access(f);return true}catch{return false}}
async function readJson(f){return JSON.parse(await fs.readFile(f,'utf8'))}
async function writeJson(f,d){await fs.writeFile(f,JSON.stringify(d,null,2)+'\n')}
async function managed(file,heading,replacement){const cur=await fs.readFile(file,'utf8'); const next=cur.includes(heading)?cur.replace(new RegExp(`${esc(heading)}[\\s\\S]*$`,'m'),replacement):`${cur.trimEnd()}\n\n${replacement}`; await fs.writeFile(file,next.trimEnd()+'\n')}
function p(...parts){return path.join(ROOT,...parts)}
function pos(a){return a.filter(x=>!x.startsWith('--'))}
function flag(a,n){const prefix=`--${n}=`; const inline=a.find(x=>x.startsWith(prefix)); if(inline) return inline.slice(prefix.length); const i=a.indexOf(`--${n}`); return i>=0?a[i+1]:null}
function csv(v){return v?v.split(',').map(x=>x.trim()).filter(Boolean):[]}
function titleFromSlug(s){return s.replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function status(e){return ['active','deprecated','archived'].includes(e.status)?e.status:'active'}
function esc(v){return v.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
